import { Farmer, Supplier, RawMaterialBatch, ExtractBatch, Order, TeamTask } from './types';

export const INITIAL_FARMERS: Farmer[] = [
  { 
    id: 'F001', 
    name: 'Farmer Khan', 
    cropType: 'Ashwagandha Root', 
    location: 'Mysore', 
    estimatedYield: 5000, 
    lastDeliveryDate: '2024-03-15', 
    rating: 4.8,
    email: 'khan.farmer@example.com',
    phone: '+91 98765 43210',
    address: 'Green Valley Farm, Mysore, Karnataka',
    joinedDate: '2022-01-10',
    certifications: ['Organic Certified', 'ISO 9001']
  },
  { 
    id: 'F002', 
    name: 'Suresh Gowda', 
    cropType: 'Turmeric Rhizome', 
    location: 'Hassan', 
    estimatedYield: 8000, 
    lastDeliveryDate: '2024-03-10', 
    rating: 4.5,
    email: 'suresh.gowda@example.com',
    phone: '+91 98765 43211',
    address: 'Golden Fields, Hassan, Karnataka',
    joinedDate: '2022-05-20',
    certifications: ['Fair Trade']
  },
  { 
    id: 'F003', 
    name: 'Lakshmi Devi', 
    cropType: 'Moringa Leaves', 
    location: 'Tumkur', 
    estimatedYield: 3000, 
    lastDeliveryDate: '2024-03-20', 
    rating: 4.9,
    email: 'lakshmi.devi@example.com',
    phone: '+91 98765 43212',
    address: 'Nature\'s Bounty, Tumkur, Karnataka',
    joinedDate: '2023-02-15',
    certifications: ['Organic Certified', 'GAP']
  },
  { 
    id: 'F004', 
    name: 'Rajesh Kumar', 
    cropType: 'Shilajit Raw', 
    location: 'Himalayas', 
    estimatedYield: 1500, 
    lastDeliveryDate: '2024-03-25', 
    rating: 4.7,
    email: 'rajesh.kumar@example.com',
    phone: '+91 98765 43213',
    address: 'Mountain Base Camp, Leh, Ladakh',
    joinedDate: '2021-06-12',
    certifications: ['Wild Crafted', 'ISO 9001']
  },
  { 
    id: 'F005', 
    name: 'Anita Sharma', 
    cropType: 'Marigold Flowers', 
    location: 'Pune', 
    estimatedYield: 4500, 
    lastDeliveryDate: '2024-03-28', 
    rating: 4.6,
    email: 'anita.sharma@example.com',
    phone: '+91 98765 43214',
    address: 'Floral Gardens, Pune, Maharashtra',
    joinedDate: '2022-09-05',
    certifications: ['Organic Certified']
  },
  { 
    id: 'F006', 
    name: 'Vijay Singh', 
    cropType: 'Boswellia Resin', 
    location: 'Madhya Pradesh', 
    estimatedYield: 2000, 
    lastDeliveryDate: '2024-03-30', 
    rating: 4.4,
    email: 'vijay.singh@example.com',
    phone: '+91 98765 43215',
    address: 'Forest Edge, Jabalpur, MP',
    joinedDate: '2023-01-18',
    certifications: ['Fair Trade']
  },
  { 
    id: 'F007', 
    name: 'Sunita Patil', 
    cropType: 'Garcinia Fruit', 
    location: 'Kerala', 
    estimatedYield: 6000, 
    lastDeliveryDate: '2024-04-02', 
    rating: 4.8,
    email: 'sunita.patil@example.com',
    phone: '+91 98765 43216',
    address: 'Coastal Farm, Kochi, Kerala',
    joinedDate: '2022-03-22',
    certifications: ['Organic Certified', 'HACCP']
  },
  { 
    id: 'F008', 
    name: 'Amitabh Bachchan', 
    cropType: 'Bacopa Monnieri', 
    location: 'Uttar Pradesh', 
    estimatedYield: 3500, 
    lastDeliveryDate: '2024-04-05', 
    rating: 4.9,
    email: 'amitabh.b@example.com',
    phone: '+91 98765 43217',
    address: 'Ganga Banks, Varanasi, UP',
    joinedDate: '2021-11-30',
    certifications: ['Organic Certified']
  },
  { 
    id: 'F009', 
    name: 'Priya Reddy', 
    cropType: 'Tamarind Fruit', 
    location: 'Andhra Pradesh', 
    estimatedYield: 7000, 
    lastDeliveryDate: '2024-04-08', 
    rating: 4.5,
    email: 'priya.reddy@example.com',
    phone: '+91 98765 43218',
    address: 'Tamarind Grove, Guntur, AP',
    joinedDate: '2023-05-14',
    certifications: ['GAP']
  },
  { 
    id: 'F010', 
    name: 'Karan Johar', 
    cropType: 'Hibiscus Flowers', 
    location: 'Tamil Nadu', 
    estimatedYield: 2500, 
    lastDeliveryDate: '2024-04-10', 
    rating: 4.7,
    email: 'karan.j@example.com',
    phone: '+91 98765 43219',
    address: 'Bloom Valley, Madurai, TN',
    joinedDate: '2022-07-08',
    certifications: ['Organic Certified']
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  { 
    id: 'S001', 
    name: 'Global Botanics Ltd', 
    country: 'Germany', 
    productType: 'Concentrated Extracts', 
    pricePerKg: 1200, 
    leadTime: 14, 
    rating: 4.7,
    email: 'info@globalbotanics.de',
    phone: '+49 123 456789',
    address: 'Botanical Park 42, Berlin, Germany',
    joinedDate: '2021-11-05',
    certifications: ['GMP', 'ISO 22000']
  },
  { 
    id: 'S002', 
    name: 'Indo-Herbal Corp', 
    country: 'India', 
    productType: 'Powder Formulations', 
    pricePerKg: 450, 
    leadTime: 5, 
    rating: 4.3,
    email: 'contact@indoherbal.in',
    phone: '+91 80 1234 5678',
    address: 'Industrial Area, Bangalore, Karnataka',
    joinedDate: '2023-08-12',
    certifications: ['FSSAI', 'HACCP']
  },
  { 
    id: 'S003', 
    name: 'Nature Essence', 
    country: 'USA', 
    productType: 'Liquid Extracts', 
    pricePerKg: 2500, 
    leadTime: 21, 
    rating: 4.9,
    email: 'sales@natureessence.com',
    phone: '+1 555 0123',
    address: 'Green Way, Portland, Oregon',
    joinedDate: '2022-01-15',
    certifications: ['USDA Organic', 'GMP']
  },
  { 
    id: 'S004', 
    name: 'Euro Herbs', 
    country: 'France', 
    productType: 'Botanical Powders', 
    pricePerKg: 800, 
    leadTime: 10, 
    rating: 4.5,
    email: 'contact@euroherbs.fr',
    phone: '+33 1 23 45 67 89',
    address: 'Rue de la Botanique, Paris',
    joinedDate: '2021-04-20',
    certifications: ['ISO 9001', 'ECOCERT']
  },
  { 
    id: 'S005', 
    name: 'Asian Botanicals', 
    country: 'China', 
    productType: 'Standardized Extracts', 
    pricePerKg: 600, 
    leadTime: 30, 
    rating: 4.2,
    email: 'info@asianbotanicals.cn',
    phone: '+86 10 1234 5678',
    address: 'Tech Park, Shanghai',
    joinedDate: '2023-10-10',
    certifications: ['GMP', 'ISO 22000']
  }
];

export const INITIAL_RM_BATCHES: RawMaterialBatch[] = [
  { 
    id: 'RM001', 
    name: 'Ashwagandha Root - Premium', 
    quantity: 1200, 
    farmerId: 'F001', 
    receivedDate: '2024-03-25', 
    status: 'Passed', 
    qcResults: { purity: 98.5, moisture: 5.2, ashContent: 1.2, foreignMatter: 0.1 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/03/Untitled-design-34-scaled.jpg',
    storageLocation: 'Warehouse A - Cold Storage',
    harvestMethod: 'Manual Root Digging',
    dryingMethod: 'Solar Tunnel Drying',
    processingHistory: [
      { stage: 'Intake', timestamp: '2024-03-25 10:00', operator: 'John Doe', notes: 'Batch received in good condition' },
      { stage: 'Cleaning', timestamp: '2024-03-26 14:00', operator: 'Alice Smith', notes: 'Roots washed and sliced' }
    ]
  },
  { 
    id: 'RM002', 
    name: 'Turmeric Rhizome - Grade A', 
    quantity: 2500, 
    farmerId: 'F002', 
    receivedDate: '2024-03-28', 
    status: 'Awaiting Processing',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/03/nature-concept-top-view-green-leaves-texture-tr-2026-01-05-05-09-02-utc-scaled.jpg',
    storageLocation: 'Warehouse B - Dry Rack',
    harvestMethod: 'Mechanical Harvesting',
    dryingMethod: 'Natural Shade Drying'
  },
  { 
    id: 'RM003', 
    name: 'Shilajit Raw - Himalayan', 
    quantity: 500, 
    farmerId: 'F004', 
    receivedDate: '2024-03-30', 
    status: 'Passed', 
    qcResults: { purity: 99.1, moisture: 12.5, ashContent: 0.5, foreignMatter: 0.05 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/shilajit-1120x748.avif',
    storageLocation: 'Warehouse C - Secure Vault',
    harvestMethod: 'Traditional Hand Collection',
    dryingMethod: 'Natural Sun Drying'
  },
  { 
    id: 'RM004', 
    name: 'Marigold Flowers - Fresh', 
    quantity: 3000, 
    farmerId: 'F005', 
    receivedDate: '2024-04-01', 
    status: 'Passed', 
    qcResults: { purity: 97.8, moisture: 8.2, ashContent: 2.1, foreignMatter: 0.3 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/Marigold-Extract.jpg',
    storageLocation: 'Warehouse A - Cold Storage',
    harvestMethod: 'Manual Picking',
    dryingMethod: 'Dehydration Unit'
  },
  { 
    id: 'RM005', 
    name: 'Boswellia Serrata Resin', 
    quantity: 1500, 
    farmerId: 'F006', 
    receivedDate: '2024-04-02', 
    status: 'Passed', 
    qcResults: { purity: 95.5, moisture: 4.5, ashContent: 3.2, foreignMatter: 1.1 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/3.jpg',
    storageLocation: 'Warehouse B - Dry Rack',
    harvestMethod: 'Tapping Method',
    dryingMethod: 'Natural Air Drying'
  },
  { 
    id: 'RM006', 
    name: 'Garcinia Cambogia Fruit', 
    quantity: 4000, 
    farmerId: 'F007', 
    receivedDate: '2024-04-03', 
    status: 'Passed', 
    qcResults: { purity: 98.2, moisture: 10.5, ashContent: 1.8, foreignMatter: 0.2 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/4.3.jpg',
    storageLocation: 'Warehouse A - Cold Storage',
    harvestMethod: 'Manual Collection',
    dryingMethod: 'Smoke Drying'
  },
  { 
    id: 'RM007', 
    name: 'Bacopa Monnieri - Whole Herb', 
    quantity: 2000, 
    farmerId: 'F008', 
    receivedDate: '2024-04-04', 
    status: 'Passed', 
    qcResults: { purity: 96.9, moisture: 7.8, ashContent: 2.5, foreignMatter: 0.5 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/2-1.jpg',
    storageLocation: 'Warehouse B - Dry Rack',
    harvestMethod: 'Manual Harvesting',
    dryingMethod: 'Natural Shade Drying'
  },
  { 
    id: 'RM008', 
    name: 'Tamarind Fruit - Grade A', 
    quantity: 5000, 
    farmerId: 'F009', 
    receivedDate: '2024-04-05', 
    status: 'Passed', 
    qcResults: { purity: 99.5, moisture: 15.2, ashContent: 0.8, foreignMatter: 0.1 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/tamarind-fruit-concept-of-delicious-food-fresh-t-2026-01-09-08-05-17-utc-1120x747.jpg',
    storageLocation: 'Warehouse C - Ambient Storage',
    harvestMethod: 'Mechanical Shaking',
    dryingMethod: 'Natural Sun Drying'
  },
  { 
    id: 'RM009', 
    name: 'Hibiscus Flowers - Dried', 
    quantity: 1800, 
    farmerId: 'F010', 
    receivedDate: '2024-04-06', 
    status: 'Passed', 
    qcResults: { purity: 98.8, moisture: 9.1, ashContent: 1.5, foreignMatter: 0.2 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/hibiscus-tea-hibiscus-flower-and-dry-blossom-2026-01-08-08-12-27-utc-1120x747.jpg',
    storageLocation: 'Warehouse A - Cold Storage',
    harvestMethod: 'Manual Picking',
    dryingMethod: 'Natural Shade Drying'
  },
  { 
    id: 'RM010', 
    name: 'False Daisy (Bhringraj) Herb', 
    quantity: 2200, 
    farmerId: 'F003', 
    receivedDate: '2024-04-07', 
    status: 'Passed', 
    qcResults: { purity: 97.2, moisture: 8.5, ashContent: 2.8, foreignMatter: 0.4 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/false-daisy-extract-2026-01-07-00-46-50-utc-1120x747.jpg',
    storageLocation: 'Warehouse B - Dry Rack',
    harvestMethod: 'Manual Harvesting',
    dryingMethod: 'Natural Shade Drying'
  },
  { 
    id: 'RM011', 
    name: 'Grape Seeds - Premium', 
    quantity: 3500, 
    farmerId: 'F001', 
    receivedDate: '2024-04-08', 
    status: 'Passed', 
    qcResults: { purity: 99.2, moisture: 6.2, ashContent: 1.1, foreignMatter: 0.1 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/grape-seed-oil-in-small-bottle-and-bunch-of-grapes-2026-01-09-07-44-57-utc-1-1120x747.jpg',
    storageLocation: 'Warehouse C - Ambient Storage',
    harvestMethod: 'By-product Collection',
    dryingMethod: 'Mechanical Drying'
  },
  { 
    id: 'RM012', 
    name: 'Beetroot - Raw Slices', 
    quantity: 4500, 
    farmerId: 'F002', 
    receivedDate: '2024-04-09', 
    status: 'Passed', 
    qcResults: { purity: 98.9, moisture: 12.8, ashContent: 1.5, foreignMatter: 0.2 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/beetroot-powder-2026-01-07-00-47-05-utc-1-1120x747.jpg',
    storageLocation: 'Warehouse A - Cold Storage',
    harvestMethod: 'Mechanical Harvesting',
    dryingMethod: 'Dehydration Unit'
  },
  { 
    id: 'RM013', 
    name: 'Spirulina - Raw Biomass', 
    quantity: 1000, 
    farmerId: 'F003', 
    receivedDate: '2024-04-10', 
    status: 'Passed', 
    qcResults: { purity: 99.8, moisture: 5.5, ashContent: 0.2, foreignMatter: 0.01 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/round-blue-green-natural-spirulina-algae-tablets-a-2026-01-09-00-41-51-utc-1120x747.jpg',
    storageLocation: 'Warehouse C - Ambient Storage',
    harvestMethod: 'Filtration',
    dryingMethod: 'Spray Drying'
  },
  { 
    id: 'RM014', 
    name: 'Natural Pink Dye Biomass', 
    quantity: 1200, 
    farmerId: 'F005', 
    receivedDate: '2024-04-11', 
    status: 'Passed', 
    qcResults: { purity: 96.5, moisture: 9.2, ashContent: 3.1, foreignMatter: 0.8 },
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/pink-powder-dye-in-bowl-on-white-background-holi-2026-01-16-22-19-27-utc-1120x930.jpg',
    storageLocation: 'Warehouse B - Dry Rack',
    harvestMethod: 'Manual Collection',
    dryingMethod: 'Natural Shade Drying'
  }
];

export const INITIAL_EXTRACT_BATCHES: ExtractBatch[] = [
  { 
    id: 'EXT001', 
    name: 'Ashwagandha Extract 5%', 
    type: 'Extract', 
    potency: '5% Withanolides', 
    quantity: 120, 
    rawMaterialBatchId: 'RM001', 
    processedDate: '2024-04-01', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 5.2,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'Standard Profile',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-03',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/03/Untitled-design-34-scaled.jpg',
    extractionMethod: 'Ethanol Extraction',
    solventUsed: 'Food Grade Ethanol',
    yieldPercentage: 10.2,
    processingParameters: {
      temperature: '45°C',
      pressure: '1.2 bar',
      duration: '8 hours',
      equipmentId: 'EXT-UNIT-04'
    },
    allocatedOrderId: 'ORD101'
  },
  { 
    id: 'EXT002', 
    name: 'Shilajit Purified Resin', 
    type: 'Resin', 
    potency: '50% Fulvic Acid', 
    quantity: 50, 
    rawMaterialBatchId: 'RM003', 
    processedDate: '2024-04-05', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 51.5,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'N/A',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-07',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/shilajit-1120x748.avif',
    extractionMethod: 'Water Extraction',
    solventUsed: 'Purified Water',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '60°C',
      pressure: '1.0 bar',
      duration: '24 hours',
      equipmentId: 'RESIN-UNIT-01'
    }
  },
  { 
    id: 'EXT003', 
    name: 'Lutein 10% (Marigold)', 
    type: 'Extract', 
    potency: '10% Lutein', 
    quantity: 300, 
    rawMaterialBatchId: 'RM004', 
    processedDate: '2024-04-08', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 10.5,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'Standard',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-10',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/Marigold-Extract.jpg',
    extractionMethod: 'Supercritical CO2',
    solventUsed: 'CO2',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '35°C',
      pressure: '300 bar',
      duration: '4 hours',
      equipmentId: 'CO2-UNIT-02'
    }
  },
  { 
    id: 'EXT004', 
    name: 'Boswellic Acid 65%', 
    type: 'Extract', 
    potency: '65% Boswellic Acid', 
    quantity: 150, 
    rawMaterialBatchId: 'RM005', 
    processedDate: '2024-04-10', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 66.2,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'High Pinene',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-12',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/3.jpg',
    extractionMethod: 'Solvent Extraction',
    solventUsed: 'Methanol',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '50°C',
      pressure: '1.0 bar',
      duration: '12 hours',
      equipmentId: 'EXT-UNIT-01'
    }
  },
  { 
    id: 'EXT005', 
    name: 'HCA 60% (Garcinia)', 
    type: 'Extract', 
    potency: '60% HCA', 
    quantity: 400, 
    rawMaterialBatchId: 'RM006', 
    processedDate: '2024-04-12', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 61.8,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'N/A',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-14',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/4.3.jpg',
    extractionMethod: 'Water Extraction',
    solventUsed: 'Purified Water',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '80°C',
      pressure: '1.0 bar',
      duration: '6 hours',
      equipmentId: 'EXT-UNIT-05'
    }
  },
  { 
    id: 'EXT006', 
    name: 'Bacosides 20%', 
    type: 'Extract', 
    potency: '20% Bacosides', 
    quantity: 200, 
    rawMaterialBatchId: 'RM007', 
    processedDate: '2024-04-14', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 21.2,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'Standard',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-16',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/2-1.jpg',
    extractionMethod: 'Ethanol Extraction',
    solventUsed: 'Ethanol',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '45°C',
      pressure: '1.0 bar',
      duration: '10 hours',
      equipmentId: 'EXT-UNIT-04'
    }
  },
  { 
    id: 'EXT007', 
    name: 'Tamarind Seed Extract', 
    type: 'Extract', 
    potency: 'Standardized', 
    quantity: 500, 
    rawMaterialBatchId: 'RM008', 
    processedDate: '2024-04-16', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 100,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'N/A',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-18',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/tamarind-fruit-concept-of-delicious-food-fresh-t-2026-01-09-08-05-17-utc-1120x747.jpg',
    extractionMethod: 'Water Extraction',
    solventUsed: 'Purified Water',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '90°C',
      pressure: '1.0 bar',
      duration: '8 hours',
      equipmentId: 'EXT-UNIT-02'
    }
  },
  { 
    id: 'EXT008', 
    name: 'Hibiscus Anthocyanins', 
    type: 'Extract', 
    potency: '5% Anthocyanins', 
    quantity: 180, 
    rawMaterialBatchId: 'RM009', 
    processedDate: '2024-04-18', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 5.5,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'N/A',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-20',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/hibiscus-tea-hibiscus-flower-and-dry-blossom-2026-01-08-08-12-27-utc-1120x747.jpg',
    extractionMethod: 'Ethanol Extraction',
    solventUsed: 'Ethanol',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '40°C',
      pressure: '1.0 bar',
      duration: '12 hours',
      equipmentId: 'EXT-UNIT-03'
    }
  },
  { 
    id: 'EXT009', 
    name: 'Grape Seed OPC 95%', 
    type: 'Extract', 
    potency: '95% OPC', 
    quantity: 350, 
    rawMaterialBatchId: 'RM011', 
    processedDate: '2024-04-20', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 96.2,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'Standard',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-22',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/grape-seed-oil-in-small-bottle-and-bunch-of-grapes-2026-01-09-07-44-57-utc-1-1120x747.jpg',
    extractionMethod: 'Solvent Extraction',
    solventUsed: 'Acetone/Water',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '45°C',
      pressure: '1.0 bar',
      duration: '14 hours',
      equipmentId: 'EXT-UNIT-06'
    }
  },
  { 
    id: 'EXT010', 
    name: 'Beetroot Powder 10:1', 
    type: 'Powder', 
    potency: '10:1 Ratio', 
    quantity: 450, 
    rawMaterialBatchId: 'RM012', 
    processedDate: '2024-04-22', 
    status: 'Approved', 
    coaUrl: '#', 
    qcMetrics: { 
      pesticides: 'Pass', 
      heavyMetals: 'Pass', 
      hplc: 100,
      microbial: 'Pass',
      solventResidue: 'Pass',
      terpeneProfile: 'N/A',
      aflatoxins: 'Pass'
    },
    testerName: 'Dr. Sarah Chen',
    testDate: '2024-04-24',
    imageUrl: 'https://hayteinternational.com/wp-content/uploads/2026/02/beetroot-powder-2026-01-07-00-47-05-utc-1-1120x747.jpg',
    extractionMethod: 'Milling',
    solventUsed: 'None',
    yieldPercentage: 10.0,
    processingParameters: {
      temperature: '25°C',
      pressure: '1.0 bar',
      duration: '2 hours',
      equipmentId: 'MILL-UNIT-01'
    }
  }
];

export const INITIAL_ORDERS: Order[] = [
  { 
    id: 'ORD101', 
    clientName: 'Wellness Co.', 
    productName: 'Ashwagandha Extract 5%', 
    quantity: 50, 
    priority: 'High', 
    status: 'Allocated', 
    requestDate: '2024-04-05',
    allocatedBatchId: 'EXT001',
    shippingMethod: 'Air',
    trackingNumber: 'HYT-77281-EXP',
    estimatedDelivery: '2024-04-12',
    destination: 'London, UK',
    portOfExit: 'Mumbai Port',
    containerId: 'CONT-9921',
    vesselName: 'Air India Cargo 402',
    documents: {
      invoice: 'INV-101.pdf',
      packingList: 'PL-101.pdf',
      billOfLading: 'BL-101.pdf'
    }
  },
  { 
    id: 'ORD102', 
    clientName: 'PharmaPlus', 
    productName: 'Shilajit Purified Resin', 
    quantity: 20, 
    priority: 'High', 
    status: 'Confirmed', 
    requestDate: '2024-04-08',
    destination: 'New York, USA',
    shippingMethod: 'Air'
  },
  { 
    id: 'ORD103', 
    clientName: 'BioHealth', 
    productName: 'Lutein 10% (Marigold)', 
    quantity: 100, 
    priority: 'Medium', 
    status: 'Confirmed', 
    requestDate: '2024-04-10',
    destination: 'Berlin, Germany',
    shippingMethod: 'Sea'
  },
  { 
    id: 'ORD104', 
    clientName: 'NutriLife', 
    productName: 'Boswellic Acid 65%', 
    quantity: 50, 
    priority: 'High', 
    status: 'Confirmed', 
    requestDate: '2024-04-12',
    destination: 'Tokyo, Japan',
    shippingMethod: 'Air'
  },
  { 
    id: 'ORD105', 
    clientName: 'PureHerb', 
    productName: 'HCA 60% (Garcinia)', 
    quantity: 200, 
    priority: 'Low', 
    status: 'Enquiry', 
    requestDate: '2024-04-14',
    destination: 'Sydney, Australia'
  },
  { 
    id: 'ORD106', 
    clientName: 'Global Wellness', 
    productName: 'Bacosides 20%', 
    quantity: 80, 
    priority: 'Medium', 
    status: 'Enquiry', 
    requestDate: '2024-04-15',
    destination: 'Toronto, Canada'
  },
  { 
    id: 'ORD107', 
    clientName: 'Herbal Solutions', 
    productName: 'Tamarind Seed Extract', 
    quantity: 250, 
    priority: 'Low', 
    status: 'Enquiry', 
    requestDate: '2024-04-16',
    destination: 'Dubai, UAE'
  },
  { 
    id: 'ORD108', 
    clientName: 'Vitality Labs', 
    productName: 'Hibiscus Anthocyanins', 
    quantity: 40, 
    priority: 'High', 
    status: 'Enquiry', 
    requestDate: '2024-04-17',
    destination: 'Paris, France'
  },
  { 
    id: 'ORD109', 
    clientName: 'Nature First', 
    productName: 'Grape Seed OPC 95%', 
    quantity: 120, 
    priority: 'Medium', 
    status: 'Enquiry', 
    requestDate: '2024-04-18',
    destination: 'Singapore'
  },
  { 
    id: 'ORD110', 
    clientName: 'Health Gate', 
    productName: 'Beetroot Powder 10:1', 
    quantity: 300, 
    priority: 'Low', 
    status: 'Enquiry', 
    requestDate: '2024-04-19',
    destination: 'Moscow, Russia'
  }
];

export const INITIAL_TASKS: TeamTask[] = [
  { id: 'T001', team: 'Processing', description: 'Start extraction for RM002', priority: 'High', status: 'Todo', linkedId: 'RM002' },
  { id: 'T002', team: 'QC', description: 'Upload COA for EXT001', priority: 'Medium', status: 'Done', linkedId: 'EXT001' },
  { id: 'T003', team: 'Dispatch', description: 'Plan shipment for ORD101', priority: 'High', status: 'Todo', linkedId: 'ORD101' },
  { id: 'T004', team: 'Processing', description: 'Purify Shilajit Batch RM003', priority: 'High', status: 'Done', linkedId: 'RM003' },
  { id: 'T005', team: 'QC', description: 'Test Marigold Extract EXT003', priority: 'Medium', status: 'Done', linkedId: 'EXT003' },
  { id: 'T006', team: 'Dispatch', description: 'Prepare docs for ORD102', priority: 'High', status: 'Todo', linkedId: 'ORD102' }
];
